import {
	CharacterName,
	AbilityCard,
	Good,
	ExperienceCard,
} from '../models/types';

// ===== ІМЕНА ПЕРСОНАЖІВ =====
export const CHARACTER_NAMES: CharacterName[] = [
	{ id: 1, name: 'Капітан Софі Одеса' },
	{ id: 2, name: "Мак' Мара Джонсон" },
	{ id: 3, name: 'Касумі Аошіма' },
	{ id: 4, name: 'Одрі Вільямс' },
	{ id: 5, name: 'Рафаель Вієйра' },
	{ id: 6, name: 'Каннан Шарма' },
	{ id: 7, name: 'Лоран Лапуант' },
	{ id: 8, name: 'Марко Реєс' },
	{ id: 9, name: 'Грегорі Літтл' },
];

// ===== КАРТИ ЗДІБНОСТЕЙ =====
export const ABILITY_CARDS: AbilityCard[] = [
	{ id: 1, name: "Адреналін '1'" },
	{ id: 2, name: "Швидкий удар '2'" },
	{ id: 3, name: "Навчання" },
	{ id: 4, name: "Потужний удар '3'" },
	{ id: 5, name: "Ухилення" },
	{ id: 6, name: "Лікування" },
	{ id: 7, name: "Майстер на всі руки" },
	{ id: 8, name: "Зірке око" },
	{ id: 9, name: "Удосконалення '1'" },
	{ id: 10, name: "Перевтома" },
	{ id: 11, name: "Раптовий удар" },
	{ id: 12, name: "Узгоджений ремонт" },
	{ id: 13, name: "Фокусування" },
	{ id: 14, name: "Особливий ремонт" },
	{ id: 15, name: "Пильність" },
	{ id: 16, name: "Натхнення" },
	{ id: 17, name: "Захист" },
	{ id: 18, name: "Бинтування '1'" },
	{ id: 19, name: "На повну пару" },
	{ id: 20, name: "Причетність" },
	{ id: 21, name: "Смілива спроба" },
	{ id: 22, name: "Старший механік" },
	{ id: 23, name: "Єдність" },
	{ id: 24, name: "Міцне здоров'я" },
	{ id: 25, name: "Прибирання" },
	{ id: 26, name: "Перша допомога '4'" },
	{ id: 27, name: "Співчуття" },
	{ id: 28, name: "Лють" },
	{ id: 29, name: "Дисципліна" },
	{ id: 30, name: "Світова мудрість" },
	{ id: 31, name: "Молитва" },
	{ id: 32, name: "Дрібний ремонт" },
	{ id: 33, name: "Ретельне прицілювання" },
	{ id: 34, name: "Виверт" },
	{ id: 35, name: "Оборонна стійка" },
	{ id: 36, name: "Технічна підтримка" },
	{ id: 37, name: "Залізна воля" },
	{ id: 38, name: "Риболовля" },
	{ id: 39, name: "Зосереджений розум" },
	{ id: 40, name: "Перша допомога '5'" },
	{ id: 41, name: "Удосконалення '2'" },
	{ id: 42, name: "Швидкий удар '6'" },
	{ id: 43, name: "Бинтування '2'" },
	{ id: 44, name: "Потужний удар '5'" },
	{ id: 45, name: "Адреналін '4'" },
	{ id: 46, name: "Зірке око 'з текстом'" },
	{ id: 47, name: "Пустишка хитрість" },
	{ id: 48, name: "Пустишка кмітливість" },
	{ id: 49, name: "Пустишка майстерність" },
	{ id: 50, name: "Пустишка сприйняття" },
];

// ===== ТОВАРИ =====
export const GOODS: Good[] = [
	{ id: 1, name: "Інструменти", type: 'Стартова' },
	{ id: 2, name: "Глорія Вокер", type: 'Стартова' },
	{ id: 3, name: "Суп", type: 'Стартова' },
	{ id: 4, name: "Оладки", type: 'Стартова' },
	{ id: 5, name: "Плетений батіг", type: 'Зброя' },
	{ id: 6, name: "Парні кинджали", type: 'Зброя' },
	{ id: 7, name: "Зокмерський молот", type: 'Зброя' },
	{ id: 8, name: "Альзарійський тризубець", type: 'Зброя' },
	{ id: 9, name: "Духові дротики", type: 'Зброя' },
	{ id: 10, name: "Револьвер", type: 'Зброя' },
	{ id: 11, name: "Зокмерський гарпун", type: 'Зброя' },
	{ id: 12, name: "Панійський лук", type: 'Зброя' },
	{ id: 13, name: "Міфанська сокира", type: 'Зброя' },
	{ id: 14, name: "Сосиски-гриль", type: 'Рецепт' },
	{ id: 15, name: "Чай з місяць-трави", type: 'Рецепт' },
	{ id: 16, name: "Бісквіти з підливою", type: 'Рецепт' },
	{ id: 17, name: "Вівсянка", type: 'Рецепт' },
	{ id: 18, name: "Салатний мікс", type: 'Рецепт' },
	{ id: 19, name: "Печеня в горщику", type: 'Рецепт' },
	{ id: 20, name: "Мітболи", type: 'Рецепт' },
	{ id: 21, name: "Овочевий пиріг", type: 'Рецепт' },
	{ id: 22, name: "Рецепт лікувальної настоянки", type: 'Рецепт' },
	{ id: 23, name: "Рагу", type: 'Рецепт' },
	{ id: 24, name: "Торт", type: 'Рецепт' },
	{ id: 25, name: "Смажена риба", type: 'Рецепт' },
	{ id: 26, name: "Овочі на парі", type: 'Рецепт' },
	{ id: 27, name: "Лазурове кільце бігу", type: 'Спорядження' },
	{ id: 28, name: "Жилет з луски вугра", type: 'Спорядження' },
	{ id: 29, name: "Хлороформ", type: 'Спорядження' },
	{ id: 30, name: "Набір розвідника", type: 'Спорядження' },
	{ id: 31, name: "Висушена голова", type: 'Спорядження' },
	{ id: 32, name: "Аптечка", type: 'Спорядження' },
	{ id: 33, name: "Лукранський паровий двигун", type: 'Спорядження' },
	{ id: 34, name: "Лукранський котел", type: 'Спорядження' },
	{ id: 35, name: "Лукранська вудка", type: 'Спорядження' },
	{ id: 36, name: "Зокмерська куртка", type: 'Спорядження' },
	{ id: 37, name: "Бінокль", type: 'Спорядження' },
	{ id: 38, name: "Амулет лиса", type: 'Спорядження' },
	{ id: 39, name: "Чайник Кемтера", type: 'Спорядження' },
	{ id: 40, name: "Око мудрості", type: 'Спорядження' },
	{ id: 41, name: "Лукранські окуляри", type: 'Спорядження' },
	{ id: 42, name: "Набір негідника", type: 'Спорядження' },
	{ id: 43, name: "Похідна кухня", type: 'Спорядження' },
	{ id: 44, name: "Чай", type: 'Спорядження' },
	{ id: 45, name: "Шипований шкіряний жилет", type: 'Спорядження' },
	{ id: 46, name: "Шкіряна куртка", type: 'Спорядження' },
	{ id: 47, name: "Зокмерські рукавиці", type: 'Спорядження' },
	{ id: 48, name: "Жилет з луски змія", type: 'Спорядження' },
	{ id: 49, name: "Співаючий кулон", type: 'Спорядження' },
	{ id: 50, name: "Альзарійська кулінарна книга", type: 'Спорядження' },
	{ id: 51, name: "Набір мандрівника", type: 'Спорядження' },
	{ id: 52, name: "Обшивка корпусу", type: 'Спорядження' },
	{ id: 53, name: "Ліхтар", type: 'Спорядження' },
	{ id: 54, name: "Панійський щит", type: 'Спорядження' }
];

type StaticEventCard = {
	id: number;
	name: string;
	type: string;
	property_constantly: boolean;
};

// ===== КАРТИ ПОДІЙ =====
export const EVENT_CARDS: StaticEventCard[] = [
	{ id: 1, name: "Неймовірна течія", type: 'помірні', property_constantly: false },
	{ id: 2, name: "Зокмерські торгівці", type: 'помірні', property_constantly: false },
	{ id: 3, name: "Техобслуговування", type: 'помірні', property_constantly: false },
	{ id: 4, name: "Тяжкий розрив стосунків", type: 'помірні', property_constantly: false },
	{ id: 5, name: "Розбитий дирижабль", type: 'помірні', property_constantly: false },
	{ id: 6, name: "Примарна гостя", type: 'помірні', property_constantly: false },
	{ id: 7, name: "Оглядова вежа", type: 'помірні', property_constantly: false },
	{ id: 8, name: "Аргументи екіпажу", type: 'помірні', property_constantly: false },
	{ id: 9, name: "Летючий уламок", type: 'помірні', property_constantly: false },
	{ id: 10, name: "Покинуте каное", type: 'помірні', property_constantly: false },
	{ id: 11, name: "Велетенський сом", type: 'помірні', property_constantly: false },
	{ id: 12, name: "Щуролюд у морі", type: 'помірні', property_constantly: true },
	{ id: 13, name: "Неспокійне море", type: 'помірні', property_constantly: false },
	{ id: 14, name: "Потойбічний шлях", type: 'помірні', property_constantly: false },
	{ id: 15, name: "Покинутий човен", type: 'помірні', property_constantly: false },
	{ id: 16, name: "Акули на полюванні", type: 'помірні', property_constantly: false },
	{ id: 17, name: "Приховані скелі", type: 'помірні', property_constantly: false },
	{ id: 18, name: "Затонулий корабель", type: 'помірні', property_constantly: false },
	{ id: 19, name: "Торгівці деревиною", type: 'помірні', property_constantly: false },
	{ id: 20, name: "Зогнилий левіафан", type: 'помірні', property_constantly: false },
	{ id: 21, name: "Уламки", type: 'помірні', property_constantly: false },
	{ id: 22, name: "Приховані запаси", type: 'помірні', property_constantly: false },
	{ id: 23, name: "Торгове судно", type: 'помірні', property_constantly: false },
	{ id: 24, name: "Моряк, що загубився", type: 'помірні', property_constantly: true },
	{ id: 25, name: "Теслярі", type: 'помірні', property_constantly: false },
	{ id: 26, name: "Торговка-зомбі", type: 'помірні', property_constantly: false },
	{ id: 27, name: "Альзарійські торговці", type: 'помірні', property_constantly: false },
	{ id: 28, name: "Сад водоростей", type: 'помірні', property_constantly: false },
	{ id: 29, name: "Нічийні запаси", type: 'помірні', property_constantly: false },
	{ id: 30, name: "Затонулий корабель*", type: 'помірні', property_constantly: false },
	{ id: 31, name: "Летюча медуза", type: 'небезпечні', property_constantly: false },
	{ id: 32, name: "Скупчення водоростей", type: 'небезпечні', property_constantly: false },
	{ id: 33, name: "Несправний котел", type: 'небезпечні', property_constantly: false },
	{ id: 34, name: "Ураганні вітри", type: 'небезпечні', property_constantly: false },
	{ id: 35, name: "Щури", type: 'небезпечні', property_constantly: true },
	{ id: 36, name: "Гніздо з коралів", type: 'небезпечні', property_constantly: false },
	{ id: 37, name: "Зіпсовані запаси", type: 'небезпечні', property_constantly: true },
	{ id: 38, name: "Дунклеостей", type: 'небезпечні', property_constantly: false },
	{ id: 39, name: "Риба, що вибухає", type: 'небезпечні', property_constantly: false },
	{ id: 40, name: "Змій-провідник", type: 'небезпечні', property_constantly: false },
	{ id: 41, name: "Щури*", type: 'небезпечні', property_constantly: true },
	{ id: 42, name: "Мегалодон", type: 'небезпечні', property_constantly: false },
	{ id: 43, name: "Кусюча морська зірка", type: 'небезпечні', property_constantly: false },
	{ id: 44, name: "Вогонь у котельні", type: 'небезпечні', property_constantly: false },
	{ id: 45, name: "Напад на торгівців", type: 'небезпечні', property_constantly: false },
	{ id: 46, name: "Поранений птах", type: 'небезпечні', property_constantly: false },
	{ id: 47, name: "Примарні спостерігачі", type: 'небезпечні', property_constantly: false },
	{ id: 48, name: "Зіпсовані запаси*", type: 'небезпечні', property_constantly: true },
	{ id: 49, name: "Ящики з вибухівкою", type: 'небезпечні', property_constantly: true },
	{ id: 50, name: "Зокмерські біженці", type: 'небезпечні', property_constantly: false },
	{ id: 51, name: "Скажені чайки", type: 'небезпечні', property_constantly: false },
	{ id: 52, name: "Зокмерські біженці*", type: 'небезпечні', property_constantly: false },
	{ id: 53, name: "Морська вежа", type: 'небезпечні', property_constantly: false },
	{ id: 54, name: "Нестерпний наспів", type: 'небезпечні', property_constantly: false },
	{ id: 55, name: "Торнадо", type: 'небезпечні', property_constantly: false },
	{ id: 56, name: "Несправний біплан", type: 'небезпечні', property_constantly: false },
	{ id: 57, name: "Одержимий екіпаж", type: 'небезпечні', property_constantly: false },
	{ id: 58, name: "Забита труба", type: 'небезпечні', property_constantly: true },
	{ id: 59, name: "Лігво чудовиська", type: 'небезпечні', property_constantly: true },
	{ id: 60, name: "Плавучий острів", type: 'небезпечні', property_constantly: true },
	{ id: 61, name: "Кисотні води", type: 'смертоносні', property_constantly: false },
	{ id: 62, name: "Кривавий місяць", type: 'смертоносні', property_constantly: false },
	{ id: 63, name: "Комахи-металоїди", type: 'смертоносні', property_constantly: false },
	{ id: 64, name: "Нічні грабіжники", type: 'смертоносні', property_constantly: false },
	{ id: 65, name: "Ліоплевродон", type: 'смертоносні', property_constantly: false },
	{ id: 66, name: "Град", type: 'смертоносні', property_constantly: false },
	{ id: 67, name: "Сварка екіпажу", type: 'смертоносні', property_constantly: false },
	{ id: 68, name: "Заражена їжа", type: 'смертоносні', property_constantly: false },
	{ id: 69, name: "Крайверн атакує", type: 'смертоносні', property_constantly: false },
	{ id: 70, name: "Велетенська черепаха", type: 'смертоносні', property_constantly: false },
	{ id: 71, name: "Ураган", type: 'смертоносні', property_constantly: false },
	{ id: 72, name: "Крайверн атакує*", type: 'смертоносні', property_constantly: false },
	{ id: 73, name: "Хворобливе повітря", type: 'смертоносні', property_constantly: false },
	{ id: 74, name: "Буря", type: 'смертоносні', property_constantly: false },
	{ id: 75, name: "Вулканічні води", type: 'смертоносні', property_constantly: false },
	{ id: 76, name: "Кошмари", type: 'смертоносні', property_constantly: false },
	{ id: 77, name: "Зокмерські грабіжники", type: 'смертоносні', property_constantly: false },
	{ id: 78, name: "Безжальні торговці", type: 'смертоносні', property_constantly: false },
	{ id: 79, name: "Запліснявілий скарб", type: 'смертоносні', property_constantly: false },
	{ id: 80, name: "Запліснявілий скарб*", type: 'смертоносні', property_constantly: false },
	{ id: 81, name: "Вогняний дощ", type: 'смертоносні', property_constantly: false },
	{ id: 82, name: "Нашестя комах", type: 'смертоносні', property_constantly: true },
	{ id: 83, name: "Блукаючий айсберг", type: 'смертоносні', property_constantly: true },
	{ id: 84, name: "Павутиння", type: 'смертоносні', property_constantly: true },
	{ id: 85, name: "Паразити", type: 'смертоносні', property_constantly: true },
	{ id: 86, name: "Спорова буря", type: 'смертоносні', property_constantly: true },
	{ id: 87, name: "Змій-мисливець", type: 'смертоносні', property_constantly: true },
	{ id: 88, name: "Морський змій", type: 'смертоносні', property_constantly: true },
	{ id: 89, name: "Проблеми з двигуном", type: 'смертоносні', property_constantly: true },
	{ id: 90, name: "Дивна хвороба", type: 'смертоносні', property_constantly: true },
	{ id: 91, name: "Незрозумілий витік", type: 'смертоносні', property_constantly: true },
	{ id: 92, name: "Грибок у вантажному відсіку", type: 'смертоносні', property_constantly: true },
];

// ===== КАРТИ ДОСВІДУ =====
export const EXPERIENCE_CARDS: ExperienceCard[] = [
	{ id: 1, name: 'Витривалість', character_name_id: 1 },
	{ id: 2, name: 'Завчасне планування', character_name_id: 1 },
	{ id: 3, name: 'Міцний горішок', character_name_id: 1 },
	{ id: 4, name: 'Казки світу', character_name_id: 2 },
	{ id: 5, name: 'Майстер шаблі', character_name_id: 2 },
	{ id: 6, name: 'Народжена виживати', character_name_id: 2 },
	{ id: 7, name: 'Обдарована', character_name_id: 3 },
	{ id: 8, name: 'Зустрічний удар', character_name_id: 3 },
	{ id: 9, name: 'Відволікання', character_name_id: 4 },
	{ id: 10, name: 'Двигун нашвидкоруч', character_name_id: 4 },
	{ id: 11, name: 'Потужний захист', character_name_id: 4 },
	{ id: 12, name: 'Групова тактика', character_name_id: 5 },
	{ id: 13, name: 'Забіяка', character_name_id: 5 },
	{ id: 14, name: 'Патрон', character_name_id: 5 },
	{ id: 15, name: 'Подвійний постріл', character_name_id: 6 },
	{ id: 16, name: 'Влучний постріл', character_name_id: 6 },
	{ id: 17, name: 'Великий улов', character_name_id: 7 },
	{ id: 18, name: 'Старий моряк', character_name_id: 7 },
	{ id: 19, name: 'Уважний', character_name_id: 7 },
	{ id: 20, name: 'Надія', character_name_id: 8 },
	{ id: 21, name: 'Пекар', character_name_id: 8 },
	{ id: 22, name: 'Кмітливий кухар', character_name_id: 8 },
	{ id: 23, name: 'Стабілізація', character_name_id: 9 },
	{ id: 24, name: 'Підгоювання', character_name_id: 9 },
];